/**
 * Agent documentation generators — pure functions that produce Markdown strings
 * describing how AI agents should manage OctoCMS content.
 *
 * Output is written to `octocms/docs/` by `scripts/generate-agent-docs.ts`
 * so it ships with the npm package.
 */

import type { CollectionField, Config } from 'octocms/types';

export const AGENT_DOCS_BANNER = `<!--
  AUTO-GENERATED FILE — DO NOT EDIT.
  Generated by scripts/generate-agent-docs.ts from cms/schema.json.
  Run \`npm run agent-docs:gen\` to regenerate.
-->

`;

/** Return a JSON-safe placeholder value string for a field (for example entries). */
export function placeholderValue(field: CollectionField, collectionNames: readonly string[]): string {
  switch (field.format) {
    case 'string':
      return field.list ? '["tag1", "tag2"]' : `"Example ${field.label.toLowerCase()}"`;
    case 'text':
      return `"Example ${field.label.toLowerCase()} text"`;
    case 'slug':
      return '"example-slug"';
    case 'url':
      return '"https://example.com"';
    case 'color':
      return '"#000000"';
    case 'boolean':
      return '"true"';
    case 'number':
      return '0';
    case 'datetime':
      return '"2024-01-01T00:00:00.000Z"';
    case 'image':
      return '"<media-entry-uuid>"';
    case 'json':
      return 'null';
    case 'markdown':
      return '"(stored in companion .md file — omitted from JSON)"';
    case 'richtext':
      return '"(stored in companion .mdx file — omitted from JSON)"';
    case 'select':
      if (field.multiple) {
        const first = field.options[0]?.value ?? 'option';
        return `["${first}"]`;
      }
      return `"${field.options[0]?.value ?? 'option'}"`;
    case 'reference': {
      const cols = field.reference?.collections ?? (field.collection ? [field.collection] : [...collectionNames]);
      const exampleKey = `"${cols[0]}-<id>.json"`;
      const cardinality = field.reference?.cardinality ?? 'many';
      return cardinality === 'one' ? exampleKey : `[${exampleKey}]`;
    }
    case 'conditional':
      return '{}';
    default:
      return '"unknown"';
  }
}

/** Return a short description of how a field format is stored in JSON. */
function formatStorageNote(field: CollectionField): string {
  switch (field.format) {
    case 'string':
      return field.list ? 'JSON array of strings' : 'plain text';
    case 'text':
      return 'plain text';
    case 'slug':
      return 'URL-safe string';
    case 'url':
      return 'URL string (http(s):// or root-relative /)';
    case 'color':
      return '#rrggbb hex string';
    case 'boolean':
      return '`"true"` or `"false"` (string, not boolean)';
    case 'number':
      return 'JSON number or `null`';
    case 'datetime':
      return 'ISO 8601 string or `null`';
    case 'image':
      return 'media entry UUID string';
    case 'json':
      return 'any valid JSON value';
    case 'markdown':
      return 'companion `.md` file (not in JSON)';
    case 'richtext':
      return 'companion `.mdx` file (not in JSON)';
    case 'select':
      return field.multiple ? 'JSON array of option values' : 'option value string';
    case 'reference': {
      const cardinality = field.reference?.cardinality ?? 'many';
      return cardinality === 'one'
        ? 'reference key string (e.g. `type-id.json`)'
        : 'JSON array of reference key strings';
    }
    case 'conditional':
      return 'JSON object (branch-dependent)';
    default:
      return 'unknown';
  }
}

// ---------------------------------------------------------------------------
// Overview generator
// ---------------------------------------------------------------------------

export function generateAgentOverview(cfg: Config, collectionNames: readonly string[]): string {
  const lines: string[] = [AGENT_DOCS_BANNER + '# OctoCMS — Content Management for AI Agents', ''];

  // Intro
  lines.push(
    'This document describes how to manage content in an OctoCMS project directly via file operations.',
    'Use it when an AI agent needs to create, read, update, or delete content entries without the admin UI.',
    '',
  );

  // Content storage
  lines.push('## How content is stored', '');
  lines.push(
    `Content lives in the \`${cfg.contentFolder}/\` directory as JSON files. Each collection has its own subfolder.`,
    '',
    '**File naming:**',
    `- **\`hasMany\` collections** (multiple entries): \`${cfg.contentFolder}/{type}/{type}-{uuid}.json\` — UUID is generated via \`crypto.randomUUID()\``,
    `- **Singleton collections** (single entry): \`${cfg.contentFolder}/{type}/{type}-0000.json\` — fixed ID \`0000\``,
    '',
  );

  // Schema source of truth
  lines.push('## Where the schema lives', '');
  lines.push(
    'The data model is defined in **`cms/schema.json`** — the source of truth. It is plain JSON, hand-editable, and the visual Content Model editor at `/cms/model` writes to the same file.',
    '',
    '`cms/octocms.config.ts` is a thin TypeScript binding that re-exports `cms/__generated__/schema.ts` (a literal-typed mirror of `cms/schema.json` regenerated by `npm run types:gen`). Editing `cms/octocms.config.ts` directly is **not** supported — edit `cms/schema.json` instead.',
    '',
    'See [editing-schema.md](./editing-schema.md) for how to edit `cms/schema.json` safely (validation invariants, regeneration commands, and migration semantics).',
    '',
  );

  // Collections summary
  lines.push('## Collections', '');
  lines.push('| Collection | Label | Type |');
  lines.push('| --- | --- | --- |');
  for (const key of collectionNames) {
    const col = cfg.collections[key];
    const kind = col.hasMany ? 'hasMany' : 'singleton';
    lines.push(`| \`${key}\` | ${col.label} | ${kind} |`);
  }
  lines.push('');

  // Entry structure
  lines.push('## Entry JSON structure', '');
  lines.push(
    'Every entry file has this shape:',
    '',
    '```json',
    '{',
    '  "sys": {',
    '    "id": "<uuid-or-fixed-id>",',
    '    "type": "<collectionName>",',
    '    "status": "draft"',
    '  },',
    '  "fields": {',
    '    "fieldName": "value"',
    '  }',
    '}',
    '```',
    '',
  );

  // Status
  lines.push('## Entry status values', '');
  lines.push('| Status | Meaning | Visible on public site |');
  lines.push('| --- | --- | --- |');
  lines.push('| `draft` | Newly created, never published | No |');
  lines.push('| `published` | Live on public site | Yes |');
  lines.push('| `changed` | Edited after publish, not yet re-published | Yes (shows latest) |');
  lines.push('| `merged` | On main branch, baseline state | Yes |');
  lines.push('| `archived` | Soft-deleted | No |');
  lines.push('');
  lines.push('When creating a new entry, set `"status": "draft"`.', '');

  // Companion files
  const hasCompanion = collectionNames.some((key) => {
    const col = cfg.collections[key];
    return Object.values(col.fields).some((f) => f.format === 'markdown' || f.format === 'richtext');
  });

  if (hasCompanion) {
    lines.push('## Companion files (markdown & richtext)', '');
    lines.push(
      'Fields with `format: "markdown"` or `format: "richtext"` are **not** stored in the JSON entry.',
      'Instead, they use companion files alongside the entry:',
      '',
      '- **Markdown:** `{type}-{id}.{fieldName}.md`',
      '- **Richtext:** `{type}-{id}.{fieldName}.mdx`',
      '',
      'Example: A post entry `post-abc123.json` with a `body` markdown field stores its content in `post-abc123.body.md` in the same directory.',
      '',
    );
  }

  // URL mapping
  const publicCollections = cfg.search?.publicCollections;
  if (publicCollections && Object.keys(publicCollections).length > 0) {
    lines.push('## URL to collection mapping', '');
    lines.push('Use this table to match a public URL to its content collection and entry:');
    lines.push('');
    lines.push('| URL pattern | Collection | How to find the entry |');
    lines.push('| --- | --- | --- |');
    for (const [colName, searchCfg] of Object.entries(publicCollections)) {
      const col = cfg.collections[colName];
      if (!col) continue;
      const params = searchCfg.urlPattern.match(/:(\w+)/g)?.map((p) => p.slice(1)) ?? [];
      const findHint =
        params.length > 0
          ? `Match \`fields.${params[0]}\` from the URL segment`
          : 'Fixed path — look up the singleton entry';
      lines.push(`| \`${searchCfg.urlPattern}\` | \`${colName}\` (${col.label}) | ${findHint} |`);
    }
    lines.push('');
  }

  // CRUD operations
  lines.push('## Creating a new entry', '');
  lines.push('1. Generate a UUID (e.g. `crypto.randomUUID()`)');
  lines.push(`2. Create \`${cfg.contentFolder}/{type}/{type}-{uuid}.json\` with the entry JSON structure above`);
  lines.push('3. Set `sys.status` to `"draft"`');
  lines.push('4. Fill in all required fields (see schema reference)');
  lines.push('5. For any markdown/richtext fields, create the companion file in the same directory');
  lines.push('6. Run `npm run types:gen` if you modified `cms/octocms.config.ts`');
  lines.push('');

  lines.push('## Updating an entry', '');
  lines.push('1. Read the JSON file');
  lines.push('2. Modify values in the `fields` object');
  lines.push('3. Write the file back');
  lines.push('4. For markdown/richtext fields, edit the companion `.md`/`.mdx` file directly');
  lines.push('');

  lines.push('## Deleting an entry', '');
  lines.push('1. Delete the JSON file');
  lines.push('2. Delete any companion files (`{type}-{id}.*.md`, `{type}-{id}.*.mdx`)');
  lines.push('');

  // Adding a collection
  lines.push('## Adding a new collection', '');
  lines.push(
    '1. Edit `cms/schema.json` — add the new collection key under `collections` (see [editing-schema.md](./editing-schema.md) for the JSON shape and validation rules)',
  );
  lines.push(`2. Create the content directory: \`${cfg.contentFolder}/{collectionName}/\``);
  lines.push(
    '3. Run `npm run types:gen` to regenerate `cms/__generated__/` (TypeScript types, query helper, literal-typed schema shim)',
  );
  lines.push('4. Run `npm run docs:gen` and `npm run agent-docs:gen` to refresh `docs/generated/` and `octocms/docs/`');
  lines.push('5. Optionally create a public page route using the `query()` API:', '');
  lines.push('```typescript');
  lines.push("import { query } from 'octocms/query';");
  lines.push('');
  lines.push("const entries = await query('collectionName')");
  lines.push("  .sort('fieldName', 'desc')");
  lines.push('  .toArray();');
  lines.push('```');
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Schema generator
// ---------------------------------------------------------------------------

export function generateAgentSchema(cfg: Config, collectionNames: readonly string[]): string {
  const lines: string[] = [AGENT_DOCS_BANNER + '# OctoCMS — Schema Reference for AI Agents', ''];

  lines.push('Per-collection field definitions and example JSON entries.', '');

  // Field format storage reference
  lines.push('## Field format storage reference', '');
  lines.push('How each field format is stored in the JSON entry file:', '');
  lines.push('| Format | Storage |');
  lines.push('| --- | --- |');
  const formatExamples: [string, string][] = [
    ['string', 'Plain text string (or JSON array when `list: true`)'],
    ['text', 'Plain text string'],
    ['markdown', 'Companion `.md` file (not in JSON `fields`)'],
    ['richtext', 'Companion `.mdx` file (not in JSON `fields`)'],
    ['boolean', '`"true"` or `"false"` (string, not JSON boolean)'],
    ['number', 'JSON number or `null`'],
    ['datetime', 'ISO 8601 string (e.g. `"2024-01-01T00:00:00.000Z"`) or `null`'],
    ['image', 'Media entry UUID string'],
    ['json', 'Any valid JSON value'],
    ['slug', 'URL-safe string'],
    ['select', 'Option value string (or JSON array when `multiple: true`)'],
    ['url', 'URL string'],
    ['color', '`#rrggbb` hex string'],
    ['reference', 'Reference key string `"type-id.json"` (or JSON array for cardinality `many`)'],
    ['conditional', 'JSON object (structure varies by branch)'],
  ];
  for (const [fmt, desc] of formatExamples) {
    lines.push(`| \`${fmt}\` | ${desc} |`);
  }
  lines.push('');

  // Per-collection sections
  for (const key of collectionNames) {
    const col = cfg.collections[key];
    const isSingleton = !col.hasMany;

    lines.push(`## ${col.label} (\`${key}\`)`, '');
    lines.push(`- **Type:** ${isSingleton ? 'singleton' : 'hasMany (multiple entries)'}`);
    lines.push(`- **Path:** \`${cfg.contentFolder}/${key}/${key}-${isSingleton ? '0000' : '<uuid>'}.json\``);

    // Companion files
    const companionFields = Object.entries(col.fields).filter(
      ([, f]) => f.format === 'markdown' || f.format === 'richtext',
    );
    if (companionFields.length > 0) {
      const companions = companionFields
        .map(([name, f]) => `\`${key}-{id}.${name}.${f.format === 'markdown' ? 'md' : 'mdx'}\``)
        .join(', ');
      lines.push(`- **Companion files:** ${companions}`);
    }
    lines.push('');

    // Field table
    lines.push('### Fields', '');
    lines.push('| Field | Label | Format | Required | Storage notes |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const [fieldName, field] of Object.entries(col.fields)) {
      const req = field.required ? 'yes' : '—';
      const storage = formatStorageNote(field);
      let extra = '';
      if (field.format === 'select') {
        const vals = field.options.map((o) => `\`${o.value}\``).join(', ');
        extra = ` Options: ${vals}.`;
        if (field.defaultOption) extra += ` Default: \`${field.defaultOption}\`.`;
        if (field.defaultOptions?.length)
          extra += ` Defaults: ${field.defaultOptions.map((v) => `\`${v}\``).join(', ')}.`;
      }
      if (field.format === 'reference') {
        const cols = field.reference?.collections ?? (field.collection ? [field.collection] : [...collectionNames]);
        extra = ` Collections: ${cols.map((c) => `\`${c}\``).join(', ')}.`;
        const card = field.reference?.cardinality ?? 'many';
        extra += ` Cardinality: \`${card}\`.`;
      }
      if (field.format === 'number') {
        const parts: string[] = [];
        if (field.min != null) parts.push(`min: ${field.min}`);
        if (field.max != null) parts.push(`max: ${field.max}`);
        if (field.valueType) parts.push(`type: ${field.valueType}`);
        if (parts.length) extra = ` ${parts.join(', ')}.`;
      }
      lines.push(`| \`${fieldName}\` | ${field.label} | \`${field.format}\` | ${req} | ${storage}${extra} |`);
    }
    lines.push('');

    // Example JSON
    lines.push('### Example entry JSON', '');
    lines.push('```json');
    lines.push('{');
    lines.push('  "sys": {');
    lines.push(`    "id": "${isSingleton ? '0000' : '<uuid>'}",`);
    lines.push(`    "type": "${key}",`);
    lines.push('    "status": "draft"');
    lines.push('  },');
    lines.push('  "fields": {');
    const jsonFields = Object.entries(col.fields).filter(([, f]) => f.format !== 'markdown' && f.format !== 'richtext');
    jsonFields.forEach(([fieldName, field], i) => {
      const val = placeholderValue(field, collectionNames);
      const comma = i < jsonFields.length - 1 ? ',' : '';
      lines.push(`    "${fieldName}": ${val}${comma}`);
    });
    lines.push('  }');
    lines.push('}');
    lines.push('```');
    lines.push('');

    // Companion file examples
    if (companionFields.length > 0) {
      for (const [fieldName, field] of companionFields) {
        const ext = field.format === 'markdown' ? 'md' : 'mdx';
        const id = isSingleton ? '0000' : '<uuid>';
        lines.push(`Companion file \`${cfg.contentFolder}/${key}/${key}-${id}.${fieldName}.${ext}\`:`, '');
        if (field.format === 'markdown') {
          lines.push('```markdown');
          lines.push(`# Example ${field.label}`);
          lines.push('');
          lines.push(`Write your ${field.label.toLowerCase()} content here in Markdown.`);
          lines.push('```');
        } else {
          lines.push('```mdx');
          lines.push(`Write your ${field.label.toLowerCase()} content here in MDX.`);
          lines.push('```');
        }
        lines.push('');
      }
    }
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Index generator
// ---------------------------------------------------------------------------

export function generateAgentIndex(): string {
  const lines: string[] = [AGENT_DOCS_BANNER + '# OctoCMS — AI Agent Documentation', ''];

  lines.push(
    'These auto-generated docs describe how AI agents can manage content in an OctoCMS project.',
    'Include them in your `AGENTS.md` or reference them directly.',
    '',
    '## Documents',
    '',
    '- **[Content Management](./overview.md)** — How to find, create, update, and delete content entries via file operations *(auto-generated)*',
    '- **[Schema Reference](./schema.md)** — Per-collection field definitions, example JSON, and file path conventions *(auto-generated)*',
    '- **[Editing the Schema](./editing-schema.md)** — How to edit `cms/schema.json` directly — file location, structure, validation invariants, and what to regenerate after editing *(hand-written, stable)*',
    '',
    '## Usage in AGENTS.md',
    '',
    "Reference these docs from your project's `AGENTS.md`:",
    '',
    '```markdown',
    '## Content Management',
    '',
    'See `octocms/docs/overview.md` and `octocms/docs/schema.md` for how to manage CMS content directly.',
    'See `octocms/docs/editing-schema.md` for how to edit `cms/schema.json`.',
    '```',
    '',
    `To regenerate after schema changes: \`npm run agent-docs:gen\``,
    '',
  );

  return lines.join('\n');
}
