/**
 * Schema documentation generator — produces `docs/generated/schema.md` from a `Config`.
 *
 * Pure function so the same output can be produced from `scripts/generate-docs.ts`
 * (filesystem write) and from `octocms/admin/actions/schema.ts` (in-memory commit
 * via `regenerateAll`).
 */

import type { CollectionField, Config } from '../../types';

export const SCHEMA_DOCS_BANNER = `<!--
  AUTO-GENERATED FILE — DO NOT EDIT.
  Generated by scripts/generate-docs.ts
-->

`;

function refSummary(reference: Record<string, unknown> | undefined): string {
  if (!reference) return '—';
  const parts: string[] = [];
  const collections = reference.collections as string[] | undefined;
  if (collections?.length) {
    parts.push(`collections: ${collections.join(', ')}`);
  }
  if (reference.cardinality != null) {
    parts.push(`cardinality: ${String(reference.cardinality)}`);
  }
  if (reference.min != null) {
    parts.push(`min: ${String(reference.min)}`);
  }
  if (reference.max != null) {
    parts.push(`max: ${String(reference.max)}`);
  }
  return parts.length ? parts.join('; ') : 'default';
}

function fieldRow(name: string, field: CollectionField): string {
  const refCell =
    field.format === 'reference'
      ? [
          refSummary(field.reference as Record<string, unknown> | undefined),
          field.collection != null ? `legacy \`collection\`: \`${String(field.collection)}\`` : '',
        ]
          .filter(Boolean)
          .join('<br>')
      : '—';
  const flags: string[] = [
    field.entryTitle ? '`entryTitle`' : '',
    field.required ? '`required`' : '',
    field.hint ? '`hint`' : '',
    field.format === 'string' && field.list ? '`list`' : '',
    field.format === 'text' && field.rows != null ? `\`rows\`: ${String(field.rows)}` : '',
    field.format === 'slug' && field.slugSource ? `\`slugSource\`: \`${field.slugSource}\`` : '',
    field.format === 'color' && field.allowInput ? '`allowInput`' : '',
    field.format === 'boolean' && field.defaultBoolean !== undefined ? '`defaultBoolean`' : '',
    field.format === 'boolean' && field.booleanLabels ? '`booleanLabels`' : '',
  ];
  if (field.format === 'select') {
    const vals = field.options.map((o) => `\`${o.value}\``).join(', ');
    flags.push(field.multiple ? '`multiple`' : '', vals ? `options: ${vals}` : '');
    if (field.defaultOption != null) {
      flags.push(`defaultOption: \`${field.defaultOption}\``);
    }
    if (field.defaultOptions?.length) {
      flags.push(`defaultOptions: ${field.defaultOptions.map((v) => `\`${v}\``).join(', ')}`);
    }
  }
  return `| \`${name}\` | ${field.label} | \`${field.format}\` | ${flags.filter(Boolean).join(', ') || '—'} | ${refCell} |`;
}

/**
 * Generate `docs/generated/schema.md` Markdown from a config.
 *
 * Caller is expected to have already run `validateConfig()` so this function
 * stays pure and does not throw on invalid input.
 */
export function generateSchemaDocs(
  cfg: Config,
  collectionNames: readonly string[],
  fieldFormats: readonly string[],
): string {
  const pointer = cfg.git.publishedPointerBranch?.trim();
  const lines: string[] = [
    SCHEMA_DOCS_BANNER + '# Schema reference',
    '',
    `_Project: ${cfg.projectName}_`,
    '',
    '## Git integration (from cms/octocms.config.ts)',
    '',
    `- **baseBranch:** \`${cfg.git.baseBranch}\` — default branch; feature branches are created from here; PRs target this ref.`,
    pointer
      ? `- **publishedPointerBranch:** \`${pointer}\` — branch that holds per-build pointer files under \`cms/pointers/\` so **Publish** does not commit to a protected base branch.`
      : '- **publishedPointerBranch:** _omitted_ — per-build pointer files under `cms/pointers/` are read and written on `baseBranch`.',
    '',
    '## Field formats (global)',
    '',
    fieldFormats.map((t) => `- \`${t}\``).join('\n'),
    '',
    '## Collections',
    '',
  ];

  for (const key of collectionNames) {
    const col = cfg.collections[key];
    const many = col.hasMany === true ? 'yes' : 'no (singleton-style)';
    lines.push(
      `### ${col.label} (\`${key}\`)`,
      '',
      `- **hasMany:** ${many}`,
      '',
      '| Field | Label | Format | Flags | Reference |',
      '| --- | --- | --- | --- | --- |',
    );
    for (const [fieldName, field] of Object.entries(col.fields).sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(fieldRow(fieldName, field));
    }
    lines.push('');
  }

  lines.push(
    '## Public site cache tags',
    '',
    "Cache your public-page data fetchers (the ones calling `query()`) with `'use cache'` and tag them with `OCTOCMS_PUBLIC_CONTENT_CACHE_TAG` (`octocms:content`) from `octocms/lib/publicContentCacheTag.ts`. The recommended shape is one async helper per page, defined inline at the top of the page file and called from both `generateMetadata` and the default export — co-located with what consumes it. A single tag covers every reader so they refresh together.",
    '',
    "After **`saveFile`**, **`newFile`** (create entry), and **`removeFile`**, `buildJsons()` calls `updateTag` for that tag and `revalidatePath('/', 'layout')`. External cache invalidation can be wired up via a Route Handler that calls `revalidateTag(tag, { expire: 0 })`.",
    '',
  );

  return lines.join('\n');
}
